### ISSUE TITLE
Dashboard - Collection is empty 

### ISSUE THREAD

**Issue by byousri** [cexbrayat/linkit#47]
Bonjour,

Je viens de faire un clone rapide, puis j'ai démarrer l'aply, ça a l'air pas mal ! good job

Par contre j'ai uns erreur au moment d'affichage  Dashboard:
IllegalArgumentException occured : Collection is empty 
Set<Badge> suggestedBadges = EnumSet.complementOf(EnumSet.copyOf(member.badges));
Ligne : 21

Je suis atterrie la par un pur hazard, car je fait des recherches sur Play, pour monter en compétence

**Comment by clacote** [comment]
Nice catch!
Ca vient d'être corrigé.
